---
name: POE-Test-Helpers
version: 0.05
author:
  - 'Sawyer <xsawyerx@cpan.org>'
abstract: Helps you test POE easily
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  MooseX::POE: 0.205
  Test::More: 0
requires:
  List::AllUtils: 0
  Moose: 0.8
  POE: 1.2
  Test::Deep: 0
  Test::Deep::NoTest: 0
configure_requires:
  Module::Build: 0.35
provides:
  POE::Test::Helpers:
    file: lib/POE/Test/Helpers.pm
    version: 0.05
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
